import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class DemoDataList {
  final IconData? icon;
  final String title;

  DemoDataList({this.icon, required this.title});

  static List<DemoDataList> data_list = [
    DemoDataList(icon: CupertinoIcons.heart_fill, title: 'Favorites'),
    DemoDataList(icon: Icons.beach_access, title: 'Beach'),
    DemoDataList(icon: Icons.fastfood, title: 'Food'),
    DemoDataList(icon: Icons.movie, title: 'Movies'),
    DemoDataList(icon: Icons.music_note, title: 'Music'),
    DemoDataList(icon: Icons.directions_run, title: 'Fitness'),
    DemoDataList(icon: Icons.local_hospital, title: 'Health'),
    DemoDataList(icon: Icons.school, title: 'Education'),
    DemoDataList(icon: Icons.local_mall, title: 'Shopping'),
    DemoDataList(icon: Icons.brush, title: 'Art'),
    DemoDataList(icon: Icons.local_pizza, title: 'Pizza'),
    DemoDataList(icon: Icons.local_bar, title: 'Bar'),
    DemoDataList(icon: Icons.local_cafe, title: 'Cafe'),
    DemoDataList(icon: Icons.directions_bike, title: 'Biking'),
    DemoDataList(icon: Icons.train, title: 'Train'),
    DemoDataList(icon: Icons.directions_bus, title: 'Bus'),
    DemoDataList(icon: Icons.directions_car, title: 'Car'),
    DemoDataList(icon: Icons.airplanemode_active, title: 'Airplane'),
    DemoDataList(icon: Icons.pets, title: 'Pets'),
    DemoDataList(icon: Icons.panorama, title: 'Panorama'),
    DemoDataList(icon: Icons.beach_access, title: 'Beach 2'),
    DemoDataList(icon: Icons.fastfood, title: 'Fast Food 2'),
    DemoDataList(icon: Icons.movie, title: 'Movies 2'),
    DemoDataList(icon: Icons.music_note, title: 'Music 2'),
    DemoDataList(icon: Icons.directions_run, title: 'Fitness 2'),
    DemoDataList(icon: Icons.local_hospital, title: 'Health 2'),
    DemoDataList(icon: Icons.school, title: 'Education 2'),
    DemoDataList(icon: Icons.local_mall, title: 'Shopping 2'),
    DemoDataList(icon: Icons.brush, title: 'Art 2'),
    DemoDataList(icon: Icons.local_pizza, title: 'Pizza 2'),
    DemoDataList(icon: Icons.local_bar, title: 'Bar 2'),
    DemoDataList(icon: Icons.local_cafe, title: 'Cafe 2'),
    DemoDataList(icon: Icons.directions_bike, title: 'Biking 2'),
    DemoDataList(icon: Icons.train, title: 'Train 2'),
    DemoDataList(icon: Icons.directions_bus, title: 'Bus 2'),
    DemoDataList(icon: Icons.directions_car, title: 'Car 2'),
    DemoDataList(icon: Icons.airplanemode_active, title: 'Airplane 2'),
    DemoDataList(icon: Icons.pets, title: 'Pets 2'),
    DemoDataList(icon: Icons.panorama, title: 'Panorama 2'),
    DemoDataList(icon: Icons.beach_access, title: 'Beach 3'),
    DemoDataList(icon: Icons.fastfood, title: 'Fast Food 3'),
    DemoDataList(icon: Icons.movie, title: 'Movies 3'),
    DemoDataList(icon: Icons.music_note, title: 'Music 3'),
    DemoDataList(icon: Icons.directions_run, title: 'Fitness 3'),
    DemoDataList(icon: Icons.local_hospital, title: 'Health 3'),
    DemoDataList(icon: CupertinoIcons.heart_solid, title: 'Love'),
    DemoDataList(icon: Icons.access_alarm, title: 'Alarm'),
    DemoDataList(icon: Icons.ac_unit, title: 'AC Unit'),
    DemoDataList(icon: Icons.account_balance, title: 'Bank'),
    DemoDataList(icon: Icons.add_location, title: 'Location'),
    DemoDataList(icon: Icons.add_shopping_cart, title: 'Shopping Cart'),
    DemoDataList(icon: Icons.attach_money, title: 'Money'),
    DemoDataList(icon: Icons.backup, title: 'Backup'),
    DemoDataList(icon: Icons.ballot, title: 'Vote'),
    DemoDataList(icon: Icons.beenhere, title: 'Been Here'),
    DemoDataList(icon: Icons.bluetooth, title: 'Bluetooth'),
    DemoDataList(icon: Icons.build, title: 'Build'),
    DemoDataList(icon: Icons.cake, title: 'Cake'),
    DemoDataList(icon: Icons.calendar_today, title: 'Calendar'),
    DemoDataList(icon: Icons.camera, title: 'Camera'),
    DemoDataList(icon: Icons.card_giftcard, title: 'Gift Card'),
    DemoDataList(icon: Icons.chat, title: 'Chat'),
    DemoDataList(icon: Icons.cloud, title: 'Cloud'),
    DemoDataList(icon: Icons.directions_boat, title: 'Boat'),
    DemoDataList(icon: Icons.domain, title: 'Domain'),
  ];
}
